from __future__ import annotations
"""
AlphaAI — Report Generator
Creates structured analysis reports in JSON and Markdown formats.
"""
import json
import logging
from datetime import datetime
from pathlib import Path

from config import config

logger = logging.getLogger("alphaai.reports")


class ReportGenerator:
    """Generates formatted analysis reports."""

    def __init__(self):
        self.output_dir = config.reports_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_markdown_report(self, analysis: dict) -> str:
        """Generate a Markdown analysis report."""
        symbol = analysis.get("symbol", "UNKNOWN")
        company = analysis.get("company_name", symbol)
        decision = analysis.get("final_decision", {})
        agents = analysis.get("agent_signals", {})

        signal = decision.get("signal", "HOLD")
        confidence = decision.get("confidence", 0)
        signal_emoji = {"STRONG_BUY": "🟢🟢", "BUY": "🟢", "HOLD": "🟡", "SELL": "🔴", "STRONG_SELL": "🔴🔴"}.get(signal, "⚪")

        lines = [
            f"# AlphaAI Analysis Report: {company} ({symbol})",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Analysis Time:** {analysis.get('elapsed_seconds', 'N/A')}s\n",
            "---\n",
            f"## 📋 Executive Summary\n",
            f"| Metric | Value |",
            f"|:---|:---|",
            f"| **Signal** | {signal_emoji} **{signal}** |",
            f"| **Confidence** | {confidence:.0f}% |",
            f"| **Overall Score** | {analysis.get('overall_score', 'N/A')}/100 |",
            f"| **Current Price** | ${analysis.get('current_price', 'N/A')} |",
            f"| **Sector** | {analysis.get('sector', 'N/A')} |",
            f"| **Industry** | {analysis.get('industry', 'N/A')} |",
            f"\n**Reasoning:** {decision.get('reasoning', 'N/A')}\n",
            "---\n",
            "## 📊 Agent Scores Overview\n",
            "| Agent | Signal | Confidence | Score |",
            "|:---|:---|:---|:---|",
        ]

        for name, sig in agents.items():
            s_emoji = {"BUY": "🟢", "SELL": "🔴", "HOLD": "🟡"}.get(sig.get("signal", ""), "⚪")
            lines.append(f"| {name} | {s_emoji} {sig.get('signal', 'N/A')} | {sig.get('confidence', 0):.0f}% | {sig.get('score', 0):.1f} |")

        # Individual agent details
        for name, sig in agents.items():
            lines.append(f"\n---\n### 🤖 {name}\n")
            lines.append(f"**Signal:** {sig.get('signal')} | **Confidence:** {sig.get('confidence', 0):.0f}% | **Score:** {sig.get('score', 0):.1f}\n")
            lines.append(f"**Analysis:** {sig.get('reasoning', 'N/A')}\n")

            km = sig.get("key_metrics", {})
            if km:
                lines.append("**Key Metrics:**\n| Metric | Value |\n|:---|:---|")
                for k, v in km.items():
                    lines.append(f"| {k} | {v} |")

            risks = sig.get("risks", [])
            if risks:
                lines.append(f"\n**Risks:** {', '.join(risks)}")
            catalysts = sig.get("catalysts", [])
            if catalysts:
                lines.append(f"\n**Catalysts:** {', '.join(catalysts)}")

        # Disclaimer
        lines.extend([
            "\n---\n",
            "## ⚠️ Disclaimer\n",
            "*This report is generated by an AI system for **educational and research purposes only**. "
            "It does NOT constitute financial advice. Always consult a qualified financial advisor before "
            "making investment decisions. Past performance does not guarantee future results.*\n",
            f"\n*Report generated by AlphaAI v1.0 — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*"
        ])

        return "\n".join(lines)

    def save_report(self, analysis: dict) -> dict:
        """Save analysis report in multiple formats."""
        symbol = analysis.get("symbol", "UNKNOWN")
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")

        # Markdown
        md_content = self.generate_markdown_report(analysis)
        md_path = self.output_dir / f"{symbol}_{ts}_report.md"
        md_path.write_text(md_content)

        # JSON
        json_path = self.output_dir / f"{symbol}_{ts}_data.json"
        json_path.write_text(json.dumps(analysis, indent=2, default=str))

        logger.info(f"📄 Reports saved: {md_path.name}, {json_path.name}")
        return {"markdown": str(md_path), "json": str(json_path), "content": md_content}


report_generator = ReportGenerator()
